export const ROUTE = {
  HOME: "/",
  LOGIN: "/login",
  SIGN_UP: "/sign-up",
  HELP_ME: "/help-me",
  HELP_ME_REGISTER: "/help-me/register",
  HELP_ME_EDIT: "/help-me/edit",
  HELP_YOU: "/help-you",
  HELP_YOU_REGISTER: "/help-you/register",
  HELP_YOU_EDIT: "/help-you/edit",
  CHAT: "/chat/0",
  MY_PAGE: "/my-page",
  MY_PAGE_EDIT: "/my-page/edit",
  MY_PAGE_Likes: "/my-page/likes",
  MY_PAGE_My_Writings: "/my-page/my-writings",
  MY_PAGE_Finished: "/my-page/finished",
  FEEDBACK: "/feedback",
} as const;
